server:
  port: 2333
lavalink:
  server:
    password: "${LAVALINK_PASSWORD}"
    sources:
      youtube: true
      soundcloud: true
    bufferDurationMs: 400
    soundcloud:
      clientId: "${SOUNDCLOUD_CLIENT_ID}"
    ratelimit:
      ipBlocks: []
      strategy: "RotateOnBan"
      searchTriggersFail: true
logging:
  level:
    root: INFO
    lavalink: INFO
